# Generated by Django 5.1.7 on 2025-11-03 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adminapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WildAnimal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "scientific_name",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("habitat", models.TextField(blank=True, null=True)),
                ("diet", models.CharField(blank=True, max_length=100, null=True)),
                ("size", models.CharField(blank=True, max_length=100, null=True)),
                ("weight", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "conservation_status",
                    models.CharField(
                        choices=[
                            ("Least Concern", "Least Concern"),
                            ("Near Threatened", "Near Threatened"),
                            ("Vulnerable", "Vulnerable"),
                            ("Endangered", "Endangered"),
                            ("Critically Endangered", "Critically Endangered"),
                            ("Extinct in the Wild", "Extinct in the Wild"),
                            ("Extinct", "Extinct"),
                        ],
                        help_text="Select conservation status according to IUCN Red List.",
                        max_length=50,
                    ),
                ),
                (
                    "conservation_source",
                    models.CharField(
                        default="IUCN Red List",
                        help_text="Specify the conservation reference source.",
                        max_length=100,
                    ),
                ),
                ("about", models.TextField(blank=True, null=True)),
                ("lifespan", models.CharField(blank=True, max_length=100, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "category",
                    models.ForeignKey(
                        help_text="Select the animal's biological category.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="animals",
                        to="adminapp.wildanimalcategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Wild Animal",
                "verbose_name_plural": "Wild Animals",
                "db_table": "wild_animal",
                "ordering": ["name"],
            },
        ),
    ]
