# Generated by Django 5.1.7 on 2025-11-03 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adminapp", "0002_wildanimal"),
    ]

    operations = [
        migrations.AddField(
            model_name="wildanimal",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Upload an image representing the animal.",
                null=True,
                upload_to="animal_images/",
            ),
        ),
    ]
