# Generated by Django 5.1.7 on 2025-11-08 04:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adminapp", "0003_wildanimal_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="TblWildLifeSanctuary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "species_count",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
                ("hectare", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "viewpoints",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of viewpoints"
                    ),
                ),
                (
                    "visitors_per_month",
                    models.PositiveIntegerField(
                        default=0, help_text="Monthly visitors count"
                    ),
                ),
                ("about", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Wild Life Sanctuary",
                "verbose_name_plural": "Wild Life Sanctuaries",
                "db_table": "wild_life_sanctuary",
            },
        ),
        migrations.CreateModel(
            name="TblSanctuaryImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="wildlife_sanctuary/")),
                ("caption", models.CharField(blank=True, max_length=200)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "sanctuary",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="adminapp.tblwildlifesanctuary",
                    ),
                ),
            ],
            options={
                "db_table": "sanctuary_images",
            },
        ),
    ]
