# Generated by Django 5.1.7 on 2025-11-08 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adminapp", "0004_tblwildlifesanctuary_tblsanctuaryimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tblwildlifesanctuary",
            name="hectare",
            field=models.PositiveIntegerField(
                default=0, help_text="Number of hectares"
            ),
        ),
    ]
