# Generated by Django 5.1.7 on 2025-11-14 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adminapp", "0006_community"),
        ("wildspotter_api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="community",
            name="joined_users",
            field=models.ManyToManyField(
                blank=True,
                related_name="joined_communities",
                to="wildspotter_api.tblregister",
            ),
        ),
    ]
