# Generated by Django 5.1.7 on 2025-11-14 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adminapp", "0007_community_joined_users"),
    ]

    operations = [
        migrations.CreateModel(
            name="Topic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Topic",
                "verbose_name_plural": "Topics",
                "db_table": "topics",
                "ordering": ["name"],
            },
        ),
    ]
