# Generated by Django 5.1.7 on 2025-11-19 06:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adminapp", "0008_topic"),
    ]

    operations = [
        migrations.CreateModel(
            name="ForestOfficer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("officer_id", models.CharField(max_length=50, unique=True)),
                ("name", models.CharField(max_length=150)),
                ("phone", models.CharField(max_length=15)),
                ("email", models.EmailField(max_length=254)),
                ("password", models.CharField(max_length=100)),
                (
                    "profile_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="officers_profile/"
                    ),
                ),
                (
                    "id_card_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="officers_idcards/"
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "verbose_name": "Forest Officer",
                "verbose_name_plural": "Forest Officers",
                "db_table": "forest_officers",
                "ordering": ["name"],
            },
        ),
    ]
