# Generated by Django 5.1.7 on 2025-11-19 06:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adminapp", "0009_forestofficer"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="forestofficer",
            options={"ordering": ["name"]},
        ),
        migrations.AddField(
            model_name="forestofficer",
            name="sanctuary",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="officers",
                to="adminapp.tblwildlifesanctuary",
            ),
        ),
        migrations.AlterField(
            model_name="forestofficer",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="forestofficer",
            name="id_card_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="officers/idcards/"
            ),
        ),
        migrations.AlterField(
            model_name="forestofficer",
            name="profile_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="officers/profile/"
            ),
        ),
    ]
