# Generated by Django 5.1.7 on 2025-11-19 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "adminapp",
            "0010_alter_forestofficer_options_forestofficer_sanctuary_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="forestofficer",
            name="id_card_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="officers_idcards/"
            ),
        ),
        migrations.AlterField(
            model_name="forestofficer",
            name="profile_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="officers_profile/"
            ),
        ),
    ]
