# Generated by Django 5.1.7 on 2025-11-19 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adminapp", "0011_alter_forestofficer_id_card_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="adminprofile",
            name="role",
            field=models.CharField(default="admin", max_length=100),
        ),
        migrations.AddField(
            model_name="forestofficer",
            name="role",
            field=models.CharField(default="forest_officer", max_length=100),
        ),
    ]
