# Generated by Django 5.1.7 on 2025-11-19 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("adminapp", "0012_adminprofile_role_forestofficer_role"),
    ]

    operations = [
        migrations.RenameField(
            model_name="adminprofile",
            old_name="password",
            new_name="admin_password",
        ),
    ]
