# Generated by Django 5.1.7 on 2025-11-22 06:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adminapp", "0013_rename_password_adminprofile_admin_password"),
    ]

    operations = [
        migrations.CreateModel(
            name="AwarenessPoster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("image", models.ImageField(upload_to="awareness_posters/")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("wildlife_protection", "Wildlife Protection"),
                            ("forest_fire", "Forest Fire Awareness"),
                            ("anti_poaching", "Anti-Poaching"),
                            ("general", "General Awareness"),
                        ],
                        default="general",
                        max_length=100,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "officer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="posters",
                        to="adminapp.forestofficer",
                    ),
                ),
            ],
            options={
                "db_table": "awareness_posters",
                "ordering": ["-created_at"],
            },
        ),
    ]
