# Generated by Django 5.1.7 on 2025-11-22 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adminapp", "0014_awarenessposter"),
    ]

    operations = [
        migrations.CreateModel(
            name="EducationalVideo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("video", models.FileField(upload_to="educational_videos/")),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True, null=True, upload_to="video_thumbnails/"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("wildlife", "Wildlife Education"),
                            ("environment", "Environmental Awareness"),
                            ("forest_rules", "Forest Rules & Safety"),
                            ("general", "General Education"),
                        ],
                        default="general",
                        max_length=100,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "officer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="videos",
                        to="adminapp.forestofficer",
                    ),
                ),
            ],
            options={
                "db_table": "educational_videos",
                "ordering": ["-created_at"],
            },
        ),
    ]
