# Generated by Django 5.1.7 on 2025-11-22 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adminapp", "0015_educationalvideo"),
    ]

    operations = [
        migrations.CreateModel(
            name="WildlifeProtectionImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, null=True)),
                ("image", models.ImageField(upload_to="wildlife_protection/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "officer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="protection_images",
                        to="adminapp.forestofficer",
                    ),
                ),
            ],
            options={
                "db_table": "wildlife_protection_images",
                "ordering": ["-created_at"],
            },
        ),
    ]
