# Generated by Django 6.0.1 on 2026-02-05 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0016_wildlifeprotectionimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='RescueTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=150)),
                ('leader_name', models.CharField(max_length=150)),
                ('contact_number', models.CharField(max_length=15)),
                ('members_count', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('officer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rescue_teams', to='adminapp.forestofficer')),
            ],
            options={
                'db_table': 'rescue_teams',
                'ordering': ['-created_at'],
            },
        ),
    ]
