# Generated by Django 5.1.7 on 2025-11-02 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TblRegister",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("username", models.CharField(max_length=50, unique=True)),
                ("email", models.EmailField(max_length=190, unique=True)),
                ("password", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "User Registration",
                "verbose_name_plural": "User Registrations",
                "db_table": "tbl_register",
                "ordering": ["username"],
            },
        ),
    ]
