# Generated by Django 5.1.7 on 2025-11-14 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wildspotter_api", "0002_journal"),
    ]

    operations = [
        migrations.AlterField(
            model_name="journal",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("Published", "Published"),
                    ("rejected", "Rejected"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
    ]
