# Generated by Django 5.1.7 on 2025-11-19 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wildspotter_api", "0003_alter_journal_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="tblregister",
            name="role",
            field=models.CharField(default="user", max_length=100),
        ),
    ]
