# Generated by Django 5.1.7 on 2025-11-20 05:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adminapp", "0013_rename_password_adminprofile_admin_password"),
        ("wildspotter_api", "0004_tblregister_role"),
    ]

    operations = [
        migrations.CreateModel(
            name="RecentSighting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("species", models.CharField(max_length=200)),
                ("location", models.CharField(max_length=255)),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="sightings_images/"
                    ),
                ),
                (
                    "video",
                    models.FileField(
                        blank=True, null=True, upload_to="sightings_videos/"
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "community",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sightings",
                        to="adminapp.community",
                    ),
                ),
                (
                    "sanctuary",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sightings",
                        to="adminapp.tblwildlifesanctuary",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sightings",
                        to="wildspotter_api.tblregister",
                    ),
                ),
            ],
            options={
                "db_table": "recent_sightings",
                "ordering": ["-created_at"],
            },
        ),
    ]
