# Generated by Django 5.1.7 on 2025-11-20 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wildspotter_api", "0005_recentsighting"),
    ]

    operations = [
        migrations.AddField(
            model_name="recentsighting",
            name="Scientific_name",
            field=models.CharField(default="", max_length=200),
            preserve_default=False,
        ),
    ]
