# Generated by Django 5.1.7 on 2025-11-21 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wildspotter_api", "0006_recentsighting_scientific_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recentsighting",
            name="community",
        ),
        migrations.RemoveField(
            model_name="recentsighting",
            name="location",
        ),
        migrations.AddField(
            model_name="recentsighting",
            name="latitude",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="recentsighting",
            name="longitude",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
