# Generated by Django 5.1.7 on 2025-11-24 10:33

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wildspotter_api", "0007_remove_recentsighting_community_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SightingRating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ]
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "sighting",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ratings",
                        to="wildspotter_api.recentsighting",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sighting_ratings",
                        to="wildspotter_api.tblregister",
                    ),
                ),
            ],
            options={
                "db_table": "sighting_ratings",
                "ordering": ["-created_at"],
                "unique_together": {("user", "sighting")},
            },
        ),
    ]
